/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Hoodie.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Hoodie(props) {
  const { nodes, materials } = useGLTF('/Hoodie.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.hoodie_low001.geometry} material={materials['Material.001']} position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.018} />
    </group>
  )
}

useGLTF.preload('/Hoodie.glb')
