/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Regular.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Regular(props) {
  const { nodes, materials } = useGLTF('/Regular.glb')
  const merchRef = useRef();
  useFrame(() => {
    if (merchRef.current && props.isRotating) {
      merchRef.current.rotation.y += 0.005;
    }
  });
  return (
    <group {...props} dispose={null} ref={merchRef}>
      <mesh geometry={nodes.Object_0001.geometry} material={materials['Material.002']} position={[0, -1.5, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.062} />
    </group>
  )
}

useGLTF.preload('/Regular.glb')
