/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Regular.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Regular(props) {
    const { nodes, materials } = useGLTF('/Regular.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Object_0001.geometry} material={materials['Material.002']} position={[0, -1.5, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.062} />
        </group>
    )
}

useGLTF.preload('/Regular.glb')
